### ISSUE TITLE
Question about number of steps

### ISSUE THREAD

**Issue by ManuelEberhardinger** [snu-mllab/Achievement-Distillation#2]
Hello, 

Thanks for sharing the code for this awesome project!

I have a question regarding the epochs and steps. So in the crafter paper they mention that they compare the performance after 1 Million interaciton steps. In your paper you also compare it with this number of steps, but in the code I only see the number of epochs. Also in Wandb the graph shows 250 steps in the end. Do you try to approximate the number of interactions steps with 250 epochs or am I missing something?

**Comment by symoon11** [comment]
Hello,

Since each epoch consumes 4096 interaction steps, 244 epochs correspond to 1M steps.
I have uploaded a file that reports the success rates and rewards at 1M interaction steps based on the log files.

Thanks
